[tool.poetry]
name = "auto-post"
version = "0.1.0"
description = ""
authors = ["Cozdig <tank-20@list.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
aiogram = "^3.22.0"
black = "^25.9.0"
python-dotenv = "^1.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
